import { FormEvent, ReactNode, useState } from 'react'

type View = 'Dashboard' | 'Budget' | 'Transactions' | 'Bills' | 'Goals' | 'Reports' | 'Settings'
type Transaction = { id: number; date: string; description: string; category: string; amount: number; type: 'Expense' | 'Income'; need: 'Need' | 'Want' }

const nav: { name: View; icon: string }[] = [
  { name: 'Dashboard', icon: '⌂' }, { name: 'Budget', icon: '▥' }, { name: 'Transactions', icon: '↕' },
  { name: 'Bills', icon: '▣' }, { name: 'Goals', icon: '♢' }, { name: 'Reports', icon: '◒' }, { name: 'Settings', icon: '⚙' },
]
const money = (value: number) => `RWF ${value.toLocaleString()}`
const initialTransactions: Transaction[] = [
  { id: 1, date: 'Sep 18', description: 'Grocery shopping', category: 'Food', amount: 48500, type: 'Expense', need: 'Need' },
  { id: 2, date: 'Sep 16', description: 'Freelance payment', category: 'Income', amount: 180000, type: 'Income', need: 'Need' },
  { id: 3, date: 'Sep 14', description: 'Motor taxi', category: 'Transport', amount: 12500, type: 'Expense', need: 'Need' },
  { id: 4, date: 'Sep 12', description: 'Streaming subscription', category: 'Entertainment', amount: 9500, type: 'Expense', need: 'Want' },
  { id: 5, date: 'Sep 10', description: 'Electricity bill', category: 'Bills', amount: 32000, type: 'Expense', need: 'Need' },
]
const budgetRows = [
  ['Food', 120000, 48500, '🍜'], ['Transport', 80000, 12500, '🚌'], ['Bills', 160000, 32000, '⚡'],
  ['Entertainment', 45000, 9500, '🎧'], ['Savings', 100000, 50000, '🌱'],
]

function App() {
  const [view, setView] = useState<View>('Dashboard')
  const [month, setMonth] = useState('September 2026')
  const [transactions, setTransactions] = useState(initialTransactions)
  const [showForm, setShowForm] = useState(false)
  const [toast, setToast] = useState('')
  const [theme, setTheme] = useState<'light' | 'dark'>('light')
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const expenses = transactions.filter(t => t.type === 'Expense').reduce((s, t) => s + t.amount, 0)
  const income = transactions.filter(t => t.type === 'Income').reduce((s, t) => s + t.amount, 0) + 450000
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600) }
  const addTransaction = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const amount = Number(data.get('amount'))
    if (!amount || amount < 1) return
    setTransactions([{ id: Date.now(), date: 'Today', description: String(data.get('description') || 'New transaction'), category: String(data.get('category')), amount, type: data.get('type') as 'Expense' | 'Income', need: data.get('need') as 'Need' | 'Want' }, ...transactions])
    setShowForm(false); notify('Transaction added successfully')
  }

  return <div className={`${theme === 'dark' ? 'app dark' : 'app'} ${sidebarCollapsed ? 'sidebar-collapsed' : ''}`}>
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark" aria-hidden="true"><span>F</span></span><span className="brand-name">Fin<b>App</b></span><button className="sidebar-toggle" aria-label={sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'} onClick={() => setSidebarCollapsed(value => !value)}>{sidebarCollapsed ? '»' : '«'}</button></div>
      <div className="profile"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><small>Personal workspace</small></div><span className="dots">•••</span></div>
      <nav>{nav.map(item => <button className={view === item.name ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.name)} key={item.name}><span>{item.icon}</span><b>{item.name}</b></button>)}</nav>
      <div className="sidebar-bottom"><div className="tip"><span>✧</span><div><b>Small steps add up</b><small>You're 24% closer to your savings goal.</small></div></div><button className="upgrade">✦ Upgrade plan <span>→</span></button></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <b>{view}</b></div><div className="top-actions"><label className="month-select">◷ <select value={month} onChange={e => setMonth(e.target.value)}><option>September 2026</option><option>August 2026</option><option>July 2026</option></select></label><span className="topbar-app-name">FinApp</span><button className="icon-button">⌕</button><button className="icon-button">♧</button></div></header>
      <div className="content">
        {view === 'Dashboard' && <Dashboard month={month} expenses={expenses} income={income} transactions={transactions} onAdd={() => setShowForm(true)} onNavigate={setView} />}
        {view === 'Budget' && <Budget onAdd={() => notify('Budget editing is ready for your next allocation.')} />}
        {view === 'Transactions' && <Transactions transactions={transactions} onAdd={() => setShowForm(true)} />}
        {view === 'Bills' && <Bills onAdd={() => notify('Bill form will be connected to your recurring bills.')} />}
        {view === 'Goals' && <Goals onAdd={() => notify('Goal creation started — set your first target.')} />}
        {view === 'Reports' && <Reports expenses={expenses} income={income} />}
        {view === 'Settings' && <Settings theme={theme} setTheme={setTheme} onSave={() => notify('Settings saved')} />}
      </div>
    </main>
    {showForm && <TransactionModal onClose={() => setShowForm(false)} onSubmit={addTransaction} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </div>
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) {
  return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>
}
function Dashboard({ month, expenses, income, transactions, onAdd, onNavigate }: { month: string; expenses: number; income: number; transactions: Transaction[]; onAdd: () => void; onNavigate: (v: View) => void }) {
  const balance = 1240000 + income - expenses
  return <><PageHeading eyebrow={month} title="Good morning, Alex" description="Here's your financial snapshot for this month." action={<button className="primary" onClick={onAdd}>＋ Add transaction</button>} />
    <section className="kpi-grid"><Kpi label="Available balance" value={money(balance)} change="+8.4%" tone="orange" icon="◉" /><Kpi label="Income" value={money(income)} change="+12.6%" tone="green" icon="↗" /><Kpi label="Expenses" value={money(expenses)} change="-4.2%" tone="blue" icon="↘" /><Kpi label="Savings" value={money(150000)} change="On track" tone="purple" icon="♡" /></section>
    <div className="dashboard-grid"><section className="card budget-card"><div className="section-title"><div><h2>Budget overview</h2><p>How you're tracking this month</p></div><button className="text-button" onClick={() => onNavigate('Budget')}>View budget →</button></div><div className="budget-total"><div><small>Spent so far</small><strong>{money(expenses)}</strong><span>of {money(505000)} planned</span></div><div className="donut"><span>47%<small>used</small></span></div></div><div className="progress wide"><span style={{ width: '47%' }} /></div><div className="legend"><span><i className="dot orange" />Spent <b>{money(expenses)}</b></span><span><i className="dot muted" />Remaining <b>{money(273500)}</b></span></div></section>
      <section className="card spending-card"><div className="section-title"><div><h2>Spending activity</h2><p>Daily outflow over the last 7 days</p></div><span className="pill">This month ▾</span></div><div className="chart"><div className="y-labels"><span>80k</span><span>40k</span><span>0</span></div><div className="bars">{[35, 50, 28, 62, 43, 76, 52].map((height, i) => <div className="bar-col" key={i}><span className="bar" style={{ height: `${height}%` }} /><small>{['12', '13', '14', '15', '16', '17', '18'][i]}</small></div>)}</div></div></section></div>
    <div className="lower-grid"><section className="card"><div className="section-title"><div><h2>Recent transactions</h2><p>Your latest money moves</p></div><button className="text-button" onClick={() => onNavigate('Transactions')}>View all →</button></div><TransactionList transactions={transactions.slice(0, 4)} /></section><section className="card goals-card"><div className="section-title"><div><h2>Savings goals</h2><p>Keep your momentum going</p></div><button className="text-button" onClick={() => onNavigate('Goals')}>View goals →</button></div><GoalMini title="Emergency fund" current={300000} target={1000000} color="orange" icon="✦" /><GoalMini title="New laptop" current={420000} target={800000} color="purple" icon="▣" /></section></div>
  </>
}
function Kpi({ label, value, change, tone, icon }: { label: string; value: string; change: string; tone: string; icon: string }) { return <div className="card kpi"><div className={`kpi-icon ${tone}`}>{icon}</div><small>{label}</small><strong>{value}</strong><span className={change.startsWith('-') ? 'negative' : 'positive'}>{change.startsWith('-') ? '↓' : '↑'} {change} <em>vs last month</em></span></div> }
function TransactionList({ transactions }: { transactions: Transaction[] }) { return <div className="transaction-list">{transactions.map(t => <div className="transaction" key={t.id}><div className={`transaction-icon ${t.category.toLowerCase()}`}>{t.category === 'Food' ? '⌁' : t.category === 'Transport' ? '↗' : t.category === 'Income' ? '↙' : t.category === 'Bills' ? 'ϟ' : '♫'}</div><div className="transaction-desc"><strong>{t.description}</strong><small>{t.date} · {t.category}</small></div><b className={t.type === 'Income' ? 'income' : ''}>{t.type === 'Income' ? '+' : '-'}{money(t.amount).replace('RWF ', 'RWF ')}</b></div>)}</div> }
function GoalMini({ title, current, target, color, icon }: { title: string; current: number; target: number; color: string; icon: string }) { return <div className="goal-mini"><div className={`goal-icon ${color}`}>{icon}</div><div className="goal-info"><strong>{title}</strong><span>{money(current)} <small>of {money(target)}</small></span><div className="progress"><span className={color} style={{ width: `${current / target * 100}%` }} /></div></div><b>{Math.round(current / target * 100)}%</b></div> }

function Budget({ onAdd }: { onAdd: () => void }) { return <><PageHeading eyebrow="September 2026" title="Monthly budget" description="Plan ahead and make every franc count." action={<button className="primary" onClick={onAdd}>＋ Edit allocations</button>} /><div className="card allocation-card"><div className="allocation-summary"><div><small>Total planned</small><strong>{money(505000)}</strong></div><div><small>Total spent</small><strong>{money(152500)}</strong></div><div><small>Remaining</small><strong className="orange-text">{money(352500)}</strong></div><div className="allocation-chart"><div className="donut small"><span>30%<small>used</small></span></div></div></div><div className="table-wrap"><table><thead><tr><th>Category</th><th>Planned</th><th>Actual</th><th>Remaining</th><th>Used</th><th>Status</th></tr></thead><tbody>{budgetRows.map(([cat, planned, actual, icon]) => { const used = Number(actual) / Number(planned) * 100; return <tr key={String(cat)}><td><span className="category-icon">{icon}</span><b>{cat}</b></td><td>{money(Number(planned))}</td><td>{money(Number(actual))}</td><td className="orange-text">{money(Number(planned) - Number(actual))}</td><td><div className="table-progress"><span style={{ width: `${used}%` }} /></div><small>{Math.round(used)}%</small></td><td><span className={`status ${used > 70 ? 'warning' : 'good'}`}>{used > 70 ? 'Watch' : 'On track'}</span></td></tr> })}</tbody></table></div></div></> }

function Transactions({ transactions, onAdd }: { transactions: Transaction[]; onAdd: () => void }) { const [query, setQuery] = useState(''); const filtered = transactions.filter(t => t.description.toLowerCase().includes(query.toLowerCase()) || t.category.toLowerCase().includes(query.toLowerCase())); return <><PageHeading title="Transactions" description="A clear history of where your money goes." action={<button className="primary" onClick={onAdd}>＋ Add transaction</button>} /><div className="card transactions-card"><div className="filters"><label className="search">⌕ <input placeholder="Search transactions" value={query} onChange={e => setQuery(e.target.value)} /></label><button className="filter-button">All types ▾</button><button className="filter-button">All categories ▾</button><button className="filter-button">September ▾</button></div><TransactionList transactions={filtered} /></div></> }
function Bills({ onAdd }: { onAdd: () => void }) { const bills = [['Rent', 'Due on 1st', 180000, 180000, 'Paid', '🏠'], ['Electricity', 'Due on 5th', 40000, 32000, 'Partial', 'ϟ'], ['Internet', 'Due on 20th', 25000, 0, 'Not paid', '⌁'], ['Water', 'Due on 25th', 12000, 0, 'Not paid', '♒']]; return <><PageHeading title="Bills" description="Stay ahead of recurring payments." action={<button className="primary" onClick={onAdd}>＋ Add bill</button>} /><div className="bill-grid">{bills.map(([name, due, planned, paid, status, icon]) => <div className="card bill-card" key={String(name)}><div className="bill-top"><span className="bill-icon">{icon}</span><span className={`status ${status === 'Paid' ? 'good' : status === 'Partial' ? 'warning' : 'neutral'}`}>{status}</span></div><h2>{name}</h2><p>{due}</p><div className="bill-amount"><span>Paid <b>{money(Number(paid))}</b></span><span>Budget <b>{money(Number(planned))}</b></span></div><div className="progress"><span style={{ width: `${Number(planned) ? Number(paid) / Number(planned) * 100 : 0}%` }} /></div></div>)}</div></> }
function Goals({ onAdd }: { onAdd: () => void }) { return <><PageHeading title="Savings goals" description="Give your money a purpose, one goal at a time." action={<button className="primary" onClick={onAdd}>＋ New goal</button>} /><div className="goal-grid"><div className="card big-goal"><div className="goal-header"><span className="goal-icon orange">✦</span><span className="status good">On track</span></div><h2>Emergency fund</h2><p>Your safety net for the unexpected</p><strong className="goal-number">{money(300000)} <small>of {money(1000000)}</small></strong><div className="progress large"><span style={{ width: '30%' }} /></div><div className="goal-meta"><span>30% complete</span><span>Target: Dec 2026</span></div><button className="secondary full">＋ Add savings</button></div><div className="card big-goal"><div className="goal-header"><span className="goal-icon purple">▣</span><span className="status warning">In progress</span></div><h2>New laptop</h2><p>Save for a better way to work</p><strong className="goal-number">{money(420000)} <small>of {money(800000)}</small></strong><div className="progress large purple-bar"><span style={{ width: '52%' }} /></div><div className="goal-meta"><span>52% complete</span><span>Target: Mar 2027</span></div><button className="secondary full">＋ Add savings</button></div></div></> }
function Reports({ expenses, income }: { expenses: number; income: number }) { return <><PageHeading eyebrow="September 2026" title="Reports" description="The story behind your money this month." action={<button className="secondary">⇩ Export report</button>} /><div className="report-grid"><div className="card report-chart"><div className="section-title"><div><h2>Income vs expenses</h2><p>Monthly comparison</p></div><span className="pill">Last 6 months ▾</span></div><div className="line-chart"><div className="line income-line" /><div className="line expense-line" />{['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'].map(m => <span key={m}>{m}</span>)}</div><div className="chart-legend"><span><i className="dot orange" />Income</span><span><i className="dot blue" />Expenses</span></div></div><div className="card insight"><span className="insight-icon">✧</span><h2>You're doing well</h2><p>Your expenses are <b>12% lower</b> than last month. At this pace, you could save an extra {money(48000)} this month.</p></div></div><div className="card category-report"><div className="section-title"><div><h2>Spending by category</h2><p>Where your money went</p></div></div>{budgetRows.slice(0, 4).map(([cat, planned, actual, icon]) => <div className="report-row" key={String(cat)}><span className="category-icon">{icon}</span><b>{cat}</b><div className="report-bar"><span style={{ width: `${Number(actual) / expenses * 100 + 15}%` }} /></div><strong>{money(Number(actual))}</strong></div>)}</div></> }
function Settings({ theme, setTheme, onSave }: { theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void; onSave: () => void }) { return <><PageHeading title="Settings" description="Make FinApp feel like yours." /><div className="settings-grid"><section className="card settings-card"><h2>Profile</h2><p>Personalise your workspace.</p><label>Full name<input defaultValue="Alex Morgan" /></label><label>Email address<input defaultValue="alex@example.com" /></label><button className="primary" onClick={onSave}>Save changes</button></section><section className="card settings-card"><h2>Appearance</h2><p>Choose how FinApp looks for you.</p><div className="theme-options"><button className={theme === 'light' ? 'theme active' : 'theme'} onClick={() => setTheme('light')}>☼<b>Light</b><small>Warm and bright</small></button><button className={theme === 'dark' ? 'theme active' : 'theme'} onClick={() => setTheme('dark')}>☾<b>Dark</b><small>Easy on the eyes</small></button></div><h2 className="settings-subtitle">Preferences</h2><label className="toggle-row">Monthly summary emails <input type="checkbox" defaultChecked /></label><label className="toggle-row">Show cents in amounts <input type="checkbox" /></label></section></div></> }
function TransactionModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={onSubmit}><div className="modal-heading"><div><span className="eyebrow">Quick entry</span><h2>Add transaction</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><div className="type-toggle"><label><input type="radio" name="type" value="Expense" defaultChecked /> Expense</label><label><input type="radio" name="type" value="Income" /> Income</label></div><label>Amount <div className="amount-input"><span>RWF</span><input name="amount" type="number" placeholder="0" autoFocus required /></div></label><label>Description<input name="description" placeholder="e.g. Lunch with a friend" required /></label><div className="form-row"><label>Category<select name="category" defaultValue="Food"><option>Food</option><option>Transport</option><option>Bills</option><option>Entertainment</option><option>Other</option></select></label><label>Need or want<select name="need" defaultValue="Need"><option>Need</option><option>Want</option></select></label></div><label>Date<input type="date" defaultValue="2026-09-18" /></label><button className="primary full" type="submit">Save transaction</button></form></div> }

export default App
